# Generated by Django 5.2.4 on 2025-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Author', models.CharField(max_length=30)),
                ('Blog_Title', models.CharField(max_length=30)),
                ('Blog_Content', models.TextField()),
            ],
        ),
    ]
