# Generated by Django 5.2.4 on 2025-09-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='Blog_Image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog_data',
            name='Created_At',
            field=models.DateField(auto_now=True),
        ),
    ]
