# Generated by Django 5.2.4 on 2025-12-02 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog_data_blog_image_blog_data_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('yapp_username', models.CharField(max_length=30, unique=True)),
                ('user_bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, default='profile_photos/default-male-profile-photo.jpg', null=True, upload_to='profile_photos/')),
                ('joined_date', models.DateField(default=datetime.date.today)),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
            ],
        ),
    ]
